work_dir: checkpoints/hysp/ntu60/xview_joint
resume_from: None   # None | path
weights: None

# training
device: 8
num_workers: 32
batch_size: 512
val_batch_size: 256
num_epoch: 600
stream: joint
hyper: true
precision: 32

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.2
lr_min: 0.
optimizer: RiemannianSGD    # SGD | RiemannianSGD
scheduler: step
step: [400]
warmup_step: 10         # only with schedule = cosine

# log
log_interval: 25
save_interval: 50
eval_interval: -1

wandb:
  enable: true
  name: HYSP - xview joint
  group: ntu60
  project: hysp
  entity: pinlab-sapienza
  save_dir: ./

# model
model: hysp
model_args:
  encoder: stgcn
  pretrain: True
  in_channels: 3
  hidden_channels: 64
  out_channels: 1024
  projection_hidden_size: [1024,1024]
  predictor_hidden_size: [1024,1024]
  moving_average_decay: 0.999
  dropout: 0.5
  graph_args:
    layout: ntu-rgb+d
    strategy: spatial
  edge_importance_weighting: True
  hyper_c: 1.

# switch from euclidean to hyperbolic
curriculum: true
initial_hyper_epoch: 50
final_hyper_epoch: 100

# feeders
train_feeder_args:
  data_path: data/action_dataset/ntu60_frame50/xview/train_position.npy
  label_path: data/action_dataset/ntu60_frame50/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True
  new_augs: False

val_feeder_args:
  data_path: data/action_dataset/ntu60_frame50/xview/val_position.npy
  label_path: data/action_dataset/ntu60_frame50/xview/val_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True
  new_augs: False