work_dir: checkpoints/hysp_xsub_joint
resume_from: None   # None | path
weights: None

# training
device: 4
num_workers: 64
batch_size: 512
val_batch_size: 512
num_epoch: 400
stream: joint
hyper: True
precision: 32

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.2
optimizer: RiemannianSGD
scheduler: step
step: [300, 400]
warmup_step: 10         # only with schedule = cosine

# log
log_interval: 25
save_interval: 25
eval_interval: -1

wandb:
  enable: True
  name: "HYSP - 60 xsub joint"
  group: dev

# model
model: hysp
model_args:
  pretrain: True
  in_channels: 3
  hidden_channels: 64
  out_channels: 1024
  projection_hidden_size: [1024,1024]
  predictor_hidden_size: [1024,1024]
  moving_average_decay: 0.999
  dropout: 0.5
  graph_args:
    layout: ntu-rgb+d
    strategy: spatial
  edge_importance_weighting: True
  hyper_c: 1.

# switch from euclidean to hyperbolic
curriculum: True
initial_hyper_epoch: 50
final_hyper_epoch: 100

# feeders
train_feeder_args:
  data_path: ./data/ntu60_frame50/xsub/train_position.npy
  label_path: ./data/ntu60_frame50/xsub/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True
  new_augs: False

val_feeder_args:
  data_path: ./data/ntu60_frame50/xsub/val_position.npy
  label_path: ./data/ntu60_frame50/xsub/val_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True
  new_augs: False