work_dir: checkpoints/pkummd_bone_2
resume_from: None   # None | path
weights: None

# training
device: [2,3,4,5]
num_workers: 32
batch_size: 512
val_batch_size: 256
num_epoch: 600
start_epoch: 0
stream: bone             # joint | motion | bone
hyper: True
precision: 32

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.4
optimizer: RiemannianSGD
scheduler: step
step: [200, 400]
warmup_step: 10

# log
log_interval: 25
save_interval: 50
eval_interval: -1

wandb:
  enable: true
  name: HYSP - PKUMMD bone 2
  group: rebuttal
  project: hysp
  entity: pinlab-sapienza

# model
model: hysp
model_args:
  pretrain: True
  in_channels: 3
  hidden_channels: 64
  out_channels: 1024
  projection_hidden_size: [1024, 1024]
  predictor_hidden_size: [1024, 1024]
  moving_average_decay: 0.999
  dropout: 0.5
  graph_args:
    layout: ntu-rgb+d
    strategy: spatial
  edge_importance_weighting: True
  hyper_c: 1.

# switch from euclidean to hyperbolic
curriculum: True
initial_hyper_epoch: 50
final_hyper_epoch: 100

# feeders

train_feeder_args:
  data_path: ./data/pku_part1_frame50/xsub/train_position.npy
  label_path: ./data/pku_part1_frame50/xsub/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True
  new_augs: False

val_feeder_args:
  data_path: ./data/pku_part1_frame50/xsub/val_position.npy
  label_path: ./data/pku_part1_frame50/xsub/val_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True
  new_augs: False