work_dir: checkpoints/hysp_pku1_to_pku2
weights: checkpoints/pkummd_joint/epoch-300.ckpt
ignore_weights: [online_projector, online_predictor, target_encoder, target_projector, queue]

# training
device: [3]
batch_size: 256
num_workers: 24
test_batch_size: 64
num_epoch: 250
stream: joint             # joint | motion | bone
protocol: linear          # linear | semi | supervised
hyper: false
precision: 16

# optim
nesterov: False
weight_decay: 0.0
base_lr: 10.
encoder_lr: 0.1
optimizer: SGD    # SGD | RiemannianSGD
step: [150, 200] # [30, 50, 70, 90] | [150, 200] | [150, 200]

# model
model: hysp
model_args:
  pretrain: False
  base_encoder: stgcn
  in_channels: 3
  hidden_channels: 64
  out_channels: 1024
  num_classes: 60
  graph_args:
    layout: ntu-rgb+d
    strategy: spatial
  edge_importance_weighting: True
  hyper_c: 1.

# log
save_interval: -1
eval_interval: 5
wandb:
  enable: False

# feeder
train_feeder_args:
  data_path: ./data/pku_part2_frame50/xsub/train_data.npy
  label_path: ./data/pku_part2_frame50/xsub/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder_args:
  data_path: ./data/pku_part2_frame50/xsub/val_data.npy
  label_path: ./data/pku_part2_frame50/xsub/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
